name: CI
on: [push, workflow_dispatch]
jobs:
    build:
        name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ['14.x']
                os: [ubuntu-latest]

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: Clean pnpm cache
              run: pnpm cache clean

            - name: Install deps (no cache)
              run: pnpm install --force

            - name: Build
              run: pnpm build

            - name: Lint
              run: pnpm lint

            - name: Test
              run: pnpm test --ci --maxWorkers=2
